name: fsdl-text-recognizer-2022
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  # versioned to match Google Colab  # version also pinned in Dockerfile
  - cudatoolkit=11.6
  - cudnn=8.3.2
  - pip=21.1.3  # versioned to match Google Colab  # version also pinned in Dockerfile
